### ISSUE TITLE
Issues with FunctionsFramework::cloudEvent() 

### ISSUE THREAD

**Issue by xtfer** [GoogleCloudPlatform/functions-framework-php#159]
Having issues with FunctionsFramework::cloudEvent() as documented at https://cloud.google.com/functions/docs/create-deploy-http-php#create_your_function.

I'm calling the following:

```
FunctionsFramework::cloudEvent('eventarc-event-name', 'myFunctionName');

function myFunctionName(CloudEvent|CloudEventInterface $event)
```

First issue Im having is that it tells me I have to hint CloudEventInterface, but if I do that it wants CloudEvent instead. If I do both, I get the following error.

```
PHP message: PHP Fatal error: Uncaught Error: Call to undefined method ReflectionUnionType::getName() in /workspace/vendor/google/cloud-functions-framework/src/CloudEventFunctionWrapper.php:75 Stack trace: #0 /workspace/vendor/google/cloud-functions-framework/src/FunctionValidationTrait.php(43): Google\CloudFunctions\CloudEventFunctionWrapper->validateFirstParameter(Object(ReflectionParameter)) #1 /workspace/vendor/google/cloud-functions-framework/src/CloudEventFunctionWrapper.php(58): Google\CloudFunctions\CloudEventFunctionWrapper->validateFunctionSignature(Object(ReflectionFunction)) #2 /workspace/vendor/google/cloud-functions-framework/src/FunctionsFramework.php(35): Google\CloudFunctions\CloudEventFunctionWrapper->__construct('dicomwebImport', true) #3 /workspace/index.php(11): Google\CloudFunctions\FunctionsFramework::cloudEvent('transport-reque...', 'dicomwebImport') #4 /workspace/vendor/google/cloud-functions-framework/router.php(37): require_once('/workspace/inde...')
```

I'm not even sure how to proceed here, as this is the officially documented approach, but doesn't appear in the readme for this project at all.

**Comment by xtfer** [comment]
I may have found the issue.

`FunctionsFramework::cloudEvent($target, true)` marshals to the CloudEventInterface, but when the function is actually run via the Invoker, line 59, it marshals to CloudEvent

```php
$this->function = new CloudEventFunctionWrapper($target, false);
```

So it is not possible to call FunctionsFramework::cloudEvent() as documented.
